---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:8.1.3
  amd64: ghcr.io/hassio-addons/debian-base:8.1.3
  armv7: ghcr.io/hassio-addons/debian-base:8.1.3
codenotary:
  base_image: admin@strausfuenf.de
  signer: admin@strausfuenf.de
