---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:8.1.4
  amd64: ghcr.io/hassio-addons/debian-base:8.1.4
  armv7: ghcr.io/hassio-addons/debian-base:8.1.4
codenotary:
  base_image: admin@strausfuenf.de
  signer: admin@strausfuenf.de
