---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.4.0
  amd64: ghcr.io/hassio-addons/debian-base:7.4.0
  armv7: ghcr.io/hassio-addons/debian-base:7.4.0
codenotary:
  base_image: admin@strausfuenf.de
  signer: admin@strausfuenf.de
